"""Stage 2: train the matching model on the pairs saved by generate_pairs.py.

This stage never touches the raw multi-million-row source tables or the
blocking index -- it only loads the (much smaller, bounded) pairs files, so
it runs comfortably in memory even on a machine that couldn't hold stage 1
in RAM at the same time as stage 2.

Usage:
    python train.py --output-dir output
"""
import argparse
from pathlib import Path

from src.config import PipelineConfig
from src.training import load_pairs, pairs_to_xy, train_model
from src.evaluation import choose_threshold_from_pairs
from src.io_utils import load_truth_json, save_json


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train the matching model on pairs generated by generate_pairs.py."
    )
    parser.add_argument("--output-dir", default="output")
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help="Skip validation-based threshold selection and use this fixed value instead.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    config = PipelineConfig()
    output_dir = Path(args.output_dir)

    print("Loading training pairs...")
    train_pairs = load_pairs(output_dir / "train_pairs.tsv")
    X, y, _ = pairs_to_xy(train_pairs)
    del train_pairs
    print(f"  {X.shape[0]:,} pairs, {X.shape[1]} features")
    print(f"  Positive rate: {y.mean():.4f}" if len(y) else "  Positive rate: 0")

    print("Training model...")
    model = train_model(X, y, config)
    del X, y

    if args.threshold is None:
        print("Loading validation pairs and selecting threshold via macro F0.5...")
        validation_pairs = load_pairs(output_dir / "validation_pairs.tsv")
        validation_truth = load_truth_json(output_dir / "validation_truth.json")

        validation_score, threshold = choose_threshold_from_pairs(
            model, validation_pairs, validation_truth, config
        )
        del validation_pairs

        print(f"Validation macro F0.5: {validation_score:.6f}")
        print(f"Selected threshold: {threshold:.3f}")
    else:
        threshold = args.threshold
        validation_score = None
        print(f"Using supplied threshold: {threshold:.3f}")

    model_path = output_dir / "model.json"
    model.save_model(model_path)

    save_json(
        {"threshold": threshold, "validation_macro_f05": validation_score},
        output_dir / "threshold.json",
    )

    print(f"Wrote: {model_path}")
    print(f"Wrote: {output_dir / 'threshold.json'}")
    print(f"Done. Next: python predict.py --test-dir <dataset/test> --output-dir {args.output_dir}")


if __name__ == "__main__":
    main()
